### ISSUE TITLE
Proposition to add Stream-51 on continuum library

### ISSUE THREAD

**Issue by TLESORT** [tyler-hayes/Stream-51#1]
Hi, 
we are developing and maintaining a library gathering continual learning scenarios (https://github.com/Continvvm/continuum).
Would you be interested in adding your dataset into our library?

If you are interested, I will be happy to help you to create a PR to our repo :)

(if you are not interested you can just close this issue ^^)
Bye
Timothée

**Comment by tyler-hayes** [comment]
Hi @TLESORT,

We would be happy to include our dataset in your repo! 😄 Please let me know how I can help with this.

Thanks!
Tyler

**Comment by TLESORT** [comment]
May I DM you on the continualAI Slack to discuss it?

**Comment by tyler-hayes** [comment]
@TLESORT Yes, please

**Comment by TLESORT** [comment]
May I DM you on the continualAI Slack to discuss it?
